### PR TITLE
Fixes sw-exporter issue 145

### LINKED ISSUE #145: npm audit ko
node v10.3.0
npm v6.1.0
commit 3db1b803370e735530b3897268ceab9be68ea675

```bash
> npm audit

                       === npm audit security report ===

# Run  npm install --save-dev electron@2.0.2  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change

  High            Code Execution by Re-enabling Node.js integration
  Package         electron
  Dependency of   electron [dev]
  Path            electron
  More info       https://nodesecurity.io/advisories/574

  Low             Prototype Pollution
  Package         deep-extend
  Dependency of   electron [dev]
  Path            electron > electron-download > rc > deep-extend
  More info       https://nodesecurity.io/advisories/612

# Run  npm update rc --depth 6  to resolve 3 vulnerabilities

  Low             Prototype Pollution
  Package         deep-extend
  Dependency of   electron-builder [dev]
  Path            electron-builder > electron-download-tf > rc > deep-extend
  More info       https://nodesecurity.io/advisories/612

  Low             Prototype Pollution
  Package         deep-extend
  Dependency of   electron-builder [dev]
  Path            electron-builder > update-notifier > latest-version >
                  package-json > registry-auth-token > rc > deep-extend
  More info       https://nodesecurity.io/advisories/612

  Low             Prototype Pollution
  Package         deep-extend
  Dependency of   electron-builder [dev]
  Path            electron-builder > update-notifier > latest-version >
                  package-json > registry-url > rc > deep-extend
  More info       https://nodesecurity.io/advisories/612

found 5 vulnerabilities (4 low, 1 high) in 6641 scanned packages
  run `npm audit fix` to fix 3 of them.
  2 vulnerabilities require semver-major dependency updates.
```

### PR DESCRIPTION
**Pull request by gtouati**
resolves #145

### CODE REVIEW

**Comment by Xzandro** [comment]
Is this fully tested? Usually this will not work, until we recompile ALL key binaries for every platform, which is why I didnt upgrade to electron 2 yet.

**Comment by GTOU** [comment]
Both win x64 & ia32 builds (dist:winX) have been tested (nsis & portable) and I'm currently trying to test the linux build through an Ubuntu VM.

Would you have a hint for the mac build? I don't have a clue about how to proceed for this one.

**Comment by Xzandro** [comment]
I usually use a Mac VM. At some point this project would need a travis / appveyor config. Still wondering why this would work without rebuilding the binaries. Weird. Can't test this currently.

**Comment by gtouati** [comment]
I could not get the app running on Ubuntu 16.04 and 18.04 with the 0.0.23 released AppImage in the first place, is that me or is it broken?

In the end I've managed to have it run tho it implies another dependency version change ([see](https://github.com/electron-userland/electron-builder/issues/2958)) and I could not test yet the impacts on windows builds.

Hence i'd rather drop the pull request.

**Comment by Xzandro** [comment]
Thanks anyway! I will handle it if I have a bit of time. Especially a more automatic process via travis / appveyor would be great for this project so I dont have to use 2 extra VM's to build & test stuff.

**Pull request closed without merging**
