### PR TITLE
Version checker plugin

### PR DESCRIPTION
**Pull request by lanthos**
I wasn't able to find a better way to get the current app version during plugin loading other than adding it to the global object in main.js.  Let me know if there is a different way that you would like this handled and I'm happy to make any changes!

This is for issues #46

### CODE REVIEW

**Comment by Xzandro** [comment]
Hey, thanks! Didn't test it quite yet and didn't thought about it too much, but one thing: I wouldn't really check against the body.name for the app version, since it's just a coincidence, that I choose this name. The next release could be `0.0.25 - Fixes and more`. I think a better approach would be to check against the tag_name - I will make sure that this is always a plain version string.

Other than that, maybe replace the var with either const or let depending on the case so we apply a bit more modern Javascript. :)

Not really an error on your end, but I think we should consider to add the request-promise module so we can use async / wait.

**Comment by lanthos** [comment]
Good points!  I've updated it to use let instead of var and it's now checking against the tag_name instead of name.  Just saw the edit as well so will look at making this enabled by default and look into request-promise and how that works.

**Comment by Xzandro** [comment]
Thanks, this is good enough for now. Small and simple, we could reiterate it in the future so that we automatically download the files and install it, but let's not good overboard I guess. We don't update that frequently. I will merge this and close the issue and if we need more we can create a new one.

**Comment by lanthos** [comment]
sounds good!

**Comment by PeteAndersen** [comment]
Thanks @lanthos <3

**Comment by lanthos** [comment]
you're welcome! :) I use the app heavily so I'm happy to be able to help out where I can.

**Pull request merged**
