### PR TITLE
Added shortcuts and compacted mode

### PR DESCRIPTION
**Pull request by joaokamun**
Automatically closed #84 when reverting my commits. 

I've added [Mousetrap](https://github.com/ccampbell/mousetrap) package to handle shortcuts more easily. And made a few changes to my previous PR, I've removed the need to pass props to children components. 

Shortcuts added (I don't have a MacOS, so I'll glad if someone test)

`Command+s` or `Ctrl+s `= Start/Stop Proxy
`Command+b` or `Ctrl+b` = Toggle Compact Mode
`Command+[1,2,3]` or `Alt+[1,2,3]` = Navigate through routes (logs, settings, help.. respectively) 

Compact mode visually its the same from #84.

### CODE REVIEW

**Comment by Xzandro** [comment]
Hi, thanks! Works great on Windows & Mac. The only problematic thing I could think of is that nobody has knowledge of the shortcuts. Maybe we need to display them somewhere in the app.

I really like the compact mode so I wouldnt mind a visual indicator at all (like a button or something, could be something small placed somewhere). What do you think?

**Comment by Jbag1489** [comment]
I haven't looked at it yet, but I think a button would be nice. I'll
personally always use shortcuts, but I know a lot of people who aren't
"computer people" aren't big fans of them.

Also, could information about shortcuts be added to the help page?

**Comment by joaokamun** [comment]
@Xzandro @Jbag1489  Done.

**Comment by Xzandro** [comment]
Looking good! If you dont want to add something else I would squash & merge it.

**Comment by joaokamun** [comment]
Its done for me. Squash it!

**Comment by Xzandro** [comment]
Thanks!

**Pull request merged**
