### PR TITLE
Added compact mode

### PR DESCRIPTION
**Pull request by joaokamun**
@Xzandro At first, I used css media query as you suggested, but the lack of user decision of when to enter on "compact mode" was buggin me, so I made some changes to make children components gain access to a "compactMode" prop from his parent. I'm sure we can improve this somehow. What you think?

I only put a button on Logs views, but its possible to add on others views too. 

image

image

I can go back to media query if you want!

### CODE REVIEW

**Comment by Xzandro** [comment]
Its true that you can toggle elements only dependent on the width of the main container with media queries. An easier approach would have been to just set a compacted class and then hide the head / menu with CSS. I like your approach though. We have less elements in the DOM now, because we only render what's necessary.

We could think about an option for compact mode so if the user starts the app its either in compact or non-compact mode. Or even better just remember the state automatically and save it in the persistent data. Thanks for your efforts. :)

**Comment by joaokamun** [comment]
@Xzandro After read this, I really don't like my approach at all. I gave so much responsability to children components. An option will be ideal, but I think persistent data will only work if "auto start proxy" is enabled, otherwise everytime user will need to change mode, start proxy and get back to compact mode. 

I'm thinking about adding keyboard shortcut functionality. A shortcut (something like cmd/ctrl+b, idk) that toggle modes. With this we can also add shortcuts for other functions, like toggle proxy, so if we decide to persist mode state and for some reason proxy is not started, user doesn't need to toggle modes to just start proxy.

**Comment by Xzandro** [comment]
Maybe you are right. This component solution might be a bit overkill. Yea, I didnt think about it. Would be kinda stupid without the option 'Auto start proxy' enabled.

**Comment by Xzandro** [comment]
Is thgis still being worked on by you @joaokamun?

**Comment by joaokamun** [comment]
Hey @Xzandro, I`ve been busy at work these days, but Ill be back on this topic this week, maybe tomorrow. I've got a few new ideas too.

**Pull request closed without merging**
