### PR TITLE
New plugin Runlogger

### PR DESCRIPTION
**Pull request by Xzandro**
Added mapping to the global scope with come2us mapping and useful utility functions

### CODE REVIEW

**Comment by DemonSkye** [comment]
I ran giants a few times with this PR working and it seemed to do roughly the same as what was in the swproxy branch.  It didn't choke on anything, though it also didn't properly identify the craft drops every time.  

A Symbol of Harmony showed up in the logs as an "unknown drop" which is totally fine, though for the sake of completeness you could probably add a mapping for it.  In swproxy it had an output more like:

    {""item_master_type"": 29, ""item_quantity"": 9, ""item_master_id"": 4001, ""wizard_id"": <ID>}}"

Which wasn't remotely helpful either, but was easily mapped to a Symbol of harmony.  

Other than that I didn't see anything that looked wrong while reviewing this PR.

**Comment by Xzandro** [comment]
Not too big of a fan of dumping JSON into a csv. I added the craft materials to the RunLogger though.

**Comment by DemonSkye** [comment]
Giving this a test now,  I thought I had done a checkout earlier but apparently only reset to head and didn't checkout the branch.  I'll let you know once I test out some of the craft material drops.  

Thanks for the update.

**Comment by DemonSkye** [comment]
Confirming that rune pieces work as well as all three types of symbols.  Overall this does seem a bit more reliable than swproxy, I think I can switch over to using this full time.  I'll take a peek at the pull request itself in a few hours when I finish re-writing some of my own stuff.

Thanks again

**Comment by Xzandro** [comment]
Alright, sounds good. After porksmash is done reviewing this (to make sure we are on the same page with naming etc.) I will merge it into master.

**Pull request merged**
