### PR TITLE
Improvements on Rune Efficiency plugin

### PR DESCRIPTION
**Pull request by joaokamun**
I was missing rune efficiency for shop runes, so I made some improvements.

Changed rune_info to contain multiple runes and added blackmarket information. Ill add WorldBoss too (probably next day, if game give me some runes) 

Screenshot:
image

### CODE REVIEW

**Comment by joaokamun** [comment]
Added rune stars above the label and rune slot between () with main stat.

What do you guys think? 
image

**Comment by porksmash** [comment]
I like the design changes! Testing what you have so far now. I think Xzandro and I would prefer to have the additional rune sources before releasing, but we can also add these after your PR if you are not able. I have a sample with a rune drop from world boss here: https://hastebin.com/agudujuteh.json

**Comment by joaokamun** [comment]
I just added world boss based on your example. Not tested yet, but is probably working. Ill try later on another account that can go world boss.

**Comment by joaokamun** [comment]
More design changes. What you guys think? I tried to follow semantic ui as much as possible.

image

**Comment by joaokamun** [comment]
@Xzandro Changed var to let and squashed all commits into one. I think its ready to merge.

**Comment by Xzandro** [comment]
Thanks for the PR. Works like a charm.

**Comment by porksmash** [comment]
Great work 👍 thank you for the contribution

**Comment by RaspFR** [comment]
Great work guys !!!! :)
The ultimate extra info would be to highlight "Hot runes". I mean 6 stars runes with % as a main stat on slot 2,4,6. 
Something like this (sorry for the quick and dirty draw) : 
hot_rune

**Pull request merged**
