### PR TITLE
Tray Icon Support

### PR DESCRIPTION
**Pull request by Psifour**
Adds support for a tray icon in response to #147 
This will also function on Windows and MacOS (as far as I know).

Please let me know if any of this is too low-quality and I will gladly tweak it :D

### CODE REVIEW

**Comment by Xzandro** [comment]
Thanks, this looks fine. To accomplish all the feature requests of #147, this would need something like 'Minimize to tray' or similiar functionality. I don't mind to merge it in this state, although this doesn't really add too much funtionality imo.

**Comment by Psifour** [comment]
I will add minimize to tray now. I was trying to keep the diff minimal as that feature requires tweaking the config that gets saved (with a new 'minimize to tray when closed' option).

Also, I don't use JS typically so will look into getting a linter setup.

**Comment by Xzandro** [comment]
Is this still being worked on?

**Comment by Xzandro** [comment]
CLosing, since there is at least a Tray icon now and also an option to minimize to tray icon.

**Pull request closed without merging**
