### PR TITLE
Siege sword tracking

### PR DESCRIPTION
**Pull request by yahehe**
This has two main features I implemented a while ago:
* Writes a message to the UI with the number of swords used and total per guild
* Saves each guild's data to a dedicated file in the SWEX folder

Personally I think the first one is more interesting, the second is just useful for tracking. I was initially planning on writing my own service for this but got too busy.

### CODE REVIEW

**Comment by Xzandro** [comment]
Hi, thanks. Basically the same issue slike in #194 Although this is probably more universally useful. Still searching for a decent solution.

**Comment by yahehe** [comment]
Yeah I figured you'd say that about the file, makes sense to me. What if I strip out the file writing and just leave the little info message in the UI? Then it's still functional (easy access to sword count breakdown) and minimal (no dependencies or files/service calls).

**Comment by Xzandro** [comment]
I think it should be an option. Also there is an option `deleteFileOnQuit` which isnt actually used. So basically two options.

1. Enabled (should be off by default)
2. Create files for every siege / guild (off by default)

**Comment by Xzandro** [comment]
Hi, closing this in favor of the new external plugin support in the versions 0.0.25+. Read up how to create external plugins [here](https://github.com/Xzandro/sw-exporter#developing-plugins).

**Pull request closed without merging**
