### PR TITLE
Update Help.js

### PR DESCRIPTION
**Pull request by MircoBlitz**
updated ca.pem installation instructions

### CODE REVIEW

**Comment by MircoBlitz** [comment]
Oh sorry I missed a </ol>

**Comment by Xzandro** [comment]
Thanks. For the sake of completion, we probably should add instructions for Android as well, so people won't think that these are iOS only specific steps.

**Comment by MircoBlitz** [comment]
I don‘t have android and no clue with that system. (Never ever touched an android device) I thought I could save you some work, instead of just barking up the tree. Probably you include it later. I made myself a reminder so I (hopefully) don‘t pesk you again with that topic.

Thak you for the Software and your time

**Comment by Xzandro** [comment]
Alright, will merge this when I have time to add the Android part myself, thanks.

**Comment by Xzandro** [comment]
Closed in favor of #429

**Pull request closed without merging**
