### PR TITLE
Added LobbyLogger

### PR DESCRIPTION
**Pull request by joaokamun**
Added a new plugin to log the lobby, based on the issue #134.

After enabling the log, you need to make 2 steps. 
1. Visit a Lobby.
2. Open each page from the records.

Basically, when entering the lobby the logger starts to get information, and only after receiving data from the 3 pages of the records, he'll save on a csv. I don't know if this is the best approach, but its the way I've thought to maintain only one file. Each user visited will have one row, and if you visit again will be another row even when data is equal.

Caveats:
- I couldn't find the GUIDs for some arena ratings: **Beginner** and **Legend** (Probably will throw error if you visit one of these ranks)

### CODE REVIEW

**Comment by joaokamun** [comment]
@Xzandro any thoughts?

**Comment by Xzandro** [comment]
Hey, sorry for the delay. I will have a look soon.

**Comment by Xzandro** [comment]
So, I tried this and it didn't create any file for me. No error messages either. The event `GetLobbyInfo` didn't trigger for me so when should this normally happen? I goit the GetLobbyWizardLog, but nothing happend there either. I just have to got to the profile and that's it right?

**Comment by joaokamun** [comment]
You need to enter the Profile, than open the Records of the user and click on each page. (I, II, III)

**Comment by Xzandro** [comment]
I did this, but sadly nothing happened. :/

**Comment by joaokamun** [comment]
I'll check this then.. :/

**Comment by Xzandro** [comment]
To be more specific: it seems to works for other people, but not for my own Profile. Is this intentional?

**Comment by joaokamun** [comment]
@Xzandro Actually I'd never tested seeing my own lobby, but I can try adapt to this scenario also.

**Comment by woodsy1** [comment]
Hey there @joaokamun,
I had a real need for what you have done so far so thanks!
I fixed up the issues with the personal profile (with some limitations)

At the start of log_lobby_pages I added the following:
`if(this.pagesRead.length === 0){
        this.pagesRead.push(0);
        const entrySelf = {
            name: Log.wizard_name
          };
        this.temp = Object.assign(this.temp, entrySelf);
    }`

The issue was caused as a result of you were only exporting if the "pages" read was 4 and this was only achieved if log_lobby was run and for a personal profile this is never the case.

The limitations are that the fields you were getting from the log_lobby are not available. I just passed in the name as that was. 

For me thats not the biggest deal as I can join the data to a personal upload anyway :)

Also note that I think it would be very helpful to have this data as json format instead of csv. I used this converted to suit my needs in the short term but I would ask you to convert to json.
https://www.csvjson.com/csv2json

Cheers,

**Comment by woodsy1** [comment]
I also added in wizard_id as I think that will be useful for matching data down the track :)

**Comment by joaokamun** [comment]
Hi @woodsy1, thanks for find these bugs. Ill try to find some time to finish this PR with the changes you asked, I've got busy these days.

**Comment by woodsy1** [comment]
No worries I think I'll probably end up writing it more generically anyway to dump the data as I think the transformation on data should be done at the application level :)

**Comment by Xzandro** [comment]
This seems to be dry. Closing for now.

**Pull request closed without merging**
